version2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -67,100 +67,84 @@ jobs:
         run: |
           sudo chown runner:runner /etc/mecabrc
           # bundle exec rake mecab:update_mecabrc
-      # 一つ前のrspecの実行データ(spec/examples.txt)をダウンロードする
-      - name: Download spec/examples.txt
+      - name: Download previous test result
         uses: actions/download-artifact@v4
         with:
-          pattern: examples-${{ matrix.ci_node_index }}
+          pattern: test-result-${{ matrix.ci_node_index }}
           path: ${{ runner.temp }}
-      # spec/examples.txtがある場合は、再実行なので失敗したテストだけを実行する
-      # spec/examples.txtがない場合は、初回実行なのでmasterブランチのJUnit XMLデータからテストを分割して全テスト実行
-      - name: Check if only failed tests should be re-run
-        id: failed-tests-only
+      - name: Place previous test result
+        id: previous-test-result
         run: |
-          if [ -e ${{ runner.temp }}/examples-${{ matrix.ci_node_index }}/examples.txt ]; then
-            mv ${{ runner.temp }}/examples-${{ matrix.ci_node_index }}/examples.txt spec/examples.txt
-            sudo chown runner:runner spec/examples.txt
-            echo "value=true" >> $GITHUB_OUTPUT
-          else
-            echo "value=" >> $GITHUB_OUTPUT
+          if [ ! -e ${{ runner.temp }}/test-result-${{ matrix.ci_node_index }}/test_results ]; then
+            exit 0
           fi
-      # masterブランチのテスト結果(JUnit XML)をダウンロード
-      - name: Download JUnit XML reports (full test for master branch)
-        if: ${{ !steps.failed-tests-only.outputs.value }}
+          echo "failed-tests-only=true" >> $GITHUB_OUTPUT
+          if [ -f ${{ runner.temp }}/test-result-${{ matrix.ci_node_index }}/spec/examples.txt ]; then
+            mv ${{ runner.temp }}/test-result-${{ matrix.ci_node_index }}/spec/examples.txt spec/examples.txt
+            sudo chown runner:runner spec/examples.txt
+          fi
+          if [ -e ${{ runner.temp }}/test-result-${{ matrix.ci_node_index }}/test_results ]; then
+            mkdir -p test_results
+            mv ${{ runner.temp }}/test-result-${{ matrix.ci_node_index }}/test_results/* test_results/
+          fi
+          if [ -e ${{ runner.temp }}/test-result-${{ matrix.ci_node_index }}/coverage ]; then
+            mkdir -p coverage
+            mv ${{ runner.temp }}/test-result-${{ matrix.ci_node_index }}/coverage/.resultset*.json coverage/
+          fi
+          bundle exec ruby scripts/rename_and_clean_test_results.rb
+      - name: Setup DB
+        run: bundle exec rails "parallel:setup[${CI_NODE_CPU_CORES}]"
+      - name: Download all test results for default branch
+        if: ${{ !steps.previous-test-result.outputs.failed-tests-only }}
         uses: dawidd6/action-download-artifact@v5
         with:
-          name: junit-xml-reports-[0-9]+
+          name: test-result-[0-9]+
           name_is_regexp: true
-          path: ${{ runner.temp }}/junit-xml-reports-downloaded
+          path: ${{ runner.temp }}/default-branch-test-results
           branch: ${{ github.event.repository.default_branch }}
           workflow_conclusion: success
-        continue-on-error: true
-      # masterブランチのテスト結果(JUnit XML)を元にテストの実行時間が各ノードで均一になるように分割
+          if_no_artifact_found: warn
       - name: Split tests by timings
-        if: ${{ !steps.failed-tests-only.outputs.value }}
+        if: ${{ !steps.previous-test-result.outputs.failed-tests-only }}
         uses: r7kamura/split-tests-by-timings@v0
         id: split-tests
         with:
-          reports: ${{ runner.temp }}/junit-xml-reports-downloaded
+          reports: ${{ runner.temp }}/default-branch-test-results/**/test_results
           glob: spec/**/*_spec.rb
           index: ${{ matrix.ci_node_index }}
           total: ${{ env.CI_NODE_TOTAL }}
-      - name: Setup DB
-        run: bundle exec rails "parallel:setup[${CI_NODE_CPU_CORES}]"
       - name: Run rspec in parallel
-        if: ${{ !steps.failed-tests-only.outputs.value }}
+        if: ${{ !steps.previous-test-result.outputs.failed-tests-only }}
         run: bundle exec parallel_rspec -n $CI_NODE_CPU_CORES ${{ steps.split-tests.outputs.paths }}
       - name: Re-run rspec only failures
-        if: ${{ steps.failed-tests-only.outputs.value }}
+        if: ${{ steps.previous-test-result.outputs.failed-tests-only }}
         run: bundle exec rspec --only-failures --failure-exit-code=0
-      - name: Filter invalid JUnit XML reports
-        if: ${{ !steps.failed-tests-only.outputs.value }}
-        run: |
-          for file in `find test_results -type f -name '*.xml'`; do
-            xmllint --noout $file || rm -rf $file
-          done
-      # masterブランチの場合だけ全テストのJUnit XMLをアップロードする
-      # また、再実行だと失敗したテストのみの実行になりカバレッジが下がってしまうので、再実行時はアップロードしない
-      - name: Upload JUnit XML reports (full test for master branch)
-        if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref && !steps.failed-tests-only.outputs.value }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: junit-xml-reports-${{ matrix.ci_node_index }}
-          path: test_results
-          if-no-files-found: error
-      - name: Upload coverage/.resultset.json
-        if: ${{ !steps.failed-tests-only.outputs.value }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-${{ matrix.ci_node_index }}
-          path: coverage/.resultset.json
       - name: Run rspec only failures
         run: |
-          rm -rf test_results/*
-          bundle exec rspec --only-failures --format RspecJunitFormatter --out test_results/rspec.xml
-      # 再実行時に失敗したテストを実行するために保存しておく
-      - name: Upload spec/examples.txt
-        if: ${{ success() || failure() }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: examples-${{ matrix.ci_node_index }}
-          path: spec/examples.txt
-          if-no-files-found: ignore
+          bundle exec ruby scripts/rename_and_clean_test_results.rb
+          bundle exec rspec --only-failures
       - name: Filter invalid JUnit XML reports
         if: ${{ success() || failure() }}
         run: |
+          invalid_found=0
           for file in `find test_results -type f -name '*.xml'`; do
-            xmllint --noout $file || rm -rf $file
+            if ! xmllint --noout "$file" 2>/dev/null; then
+              echo "Invalid XML file found and deleted: $file"
+              rm "$file"
+              invalid_found=1
+            fi
           done
-      # report-failed-testsで使用するJUnit XMLをアップロードする
-      # こちらのJUnit XMLは失敗したテストデータだけ取得できればよいでの、初回実行・再実行どちらもアップロードする
-      - name: Upload JUnit XML reports (partial test)
+          exit $invalid_found
+      - name: Upload test result
         if: ${{ success() || failure() }}
         uses: actions/upload-artifact@v4
         with:
-          name: junit-xml-reports-partial-${{ matrix.ci_node_index }}
-          path: test_results
+          name: test-result-${{ matrix.ci_node_index }}
+          path: |
+            spec/examples.txt
+            test_results/
+            coverage/.resultset*.json
+          include-hidden-files: true
           if-no-files-found: ignore
 
   report-coverage:
@@ -172,25 +156,18 @@ jobs:
       pull-requests: write
     if: success() || failure()
     steps:
-      - name: Download all coverage artifacts
-        uses: actions/download-artifact@v4
-        with:
-          pattern: coverage-*
-      - name: Move generated files
-        run: |
-          mkdir -p ${{ runner.temp }}/coverage
-          artifacts=($(ls))
-          for artifact in "${artifacts[@]}"; do
-            mv ${artifact}/.resultset.json ${{ runner.temp }}/coverage/.resultset-${artifact}.json
-            rm -r "${artifact}"
-          done
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup rails application
         uses: ./.github/actions/setup-rails-application
-      - name: Collates all result sets
-        run: bundle exec rails "coverage:report[${{ runner.temp }}/coverage/.resultset-*.json]"
-      - name: Coverage Report by octocov
+      - name: Download all test results
+        uses: actions/download-artifact@v4
+        with:
+          pattern: test-result-*
+          path: ${{ runner.temp }}/test-results
+      - name: Aggregate all coverage resultsets
+        run: bundle exec rails "coverage:report[${{ runner.temp }}/test-results/**/coverage/.resultset*.json]"
+      - name: Report coverage by octocov
         uses: k1LoW/octocov-action@v1
       - name: Upload coverage
         uses: actions/upload-artifact@v4
@@ -230,33 +207,32 @@ jobs:
       pull-requests: write
     if: success() || failure()
     env:
-      OUTPUT_FILE_NAME: rspec_reviewdog.jsonl
+      REVIEWDOG_JSON_FILE_NAME: rspec_reviewdog.jsonl
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      - name: Setup rails application
+        uses: ./.github/actions/setup-rails-application
       - name: Setup reviewdog
         uses: reviewdog/action-setup@v1
         with:
           reviewdog_version: v0.20.0
-      - name: Setup rails application
-        uses: ./.github/actions/setup-rails-application
-      # masterブランチではなく、直前のtestジョブでアップロードしたJUnit XMLをダウンロードする
-      - name: Download JUnit XML reports (partial test)
+      - name: Download all test results
         uses: actions/download-artifact@v4
         with:
-          pattern: junit-xml-reports-partial-*
-          path: ${{ runner.temp }}/junit-xml-reports-downloaded
+          pattern: test-result-*
+          path: ${{ runner.temp }}/test-results
       - name: Generate RSspec reviewdog json
         env:
-          JUNIT_XML_FILE_PATH_PATTERN: ${{ runner.temp }}/junit-xml-reports-downloaded/**/*.xml
-          OUTPUT_FILE_PATH: ${{ runner.temp }}/${{ env.OUTPUT_FILE_NAME }}
+          JUNIT_XML_FILE_PATH_PATTERN: ${{ runner.temp }}/test-results/**/test_results/*.xml
+          REVIEWDOG_JSON_FILE_PATH: ${{ runner.temp }}/${{ env.REVIEWDOG_JSON_FILE_NAME }}
         run: bundle exec ruby scripts/generate_rspec_reviewdog_json.rb
       - name: Run rspec reviewdog
         env:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
-          OUTPUT_FILE_PATH: ${{ runner.temp }}/${{ env.OUTPUT_FILE_NAME }}
+          REVIEWDOG_JSON_FILE_PATH: ${{ runner.temp }}/${{ env.REVIEWDOG_JSON_FILE_NAME }}
         run: |
-          cat $OUTPUT_FILE_PATH | reviewdog -f=rdjsonl -reporter=github-check
+          cat $REVIEWDOG_JSON_FILE_PATH | reviewdog -f=rdjsonl -reporter=github-check
 
   build-github-pages:
     needs: report-coverage
